import { Button, VerticalBox, LineEdit} from "std-widgets.slint";

export component AppWindow inherits Window {
    
    in property <string> results: "";
    in-out property <bool> openscreen;
    callback calculate-salary(string, string, string, string);

    title: "Rusty Fire Calc";
    background: #123;
    GridLayout {
        padding: 50px;
        spacing: 32px;
        Row {
            Text {
                text: "Enter Salary";
                font-size: 32px;
                font-weight: 700;
                horizontal-alignment: center;
            }
            salary := LineEdit {
                font-size: 18px;
                horizontal-alignment: center;
                placeholder-text: "Expected Salary ($)";
                height: 40px;
                min-width: 185px;
            }
        }

        Row {
            Text {
                text: "Enter Starting Value";
                font-size: 20px;
                font-weight: 700;
                horizontal-alignment: center;
            }
            initial := LineEdit {
                font-size: 18px;
                horizontal-alignment: center;
                placeholder-text: "Initial Investment ($)";
                height: 40px;
                min-width: 100px;
            }
        }

        Row {
            Text {
                text: "Enter Expected Rate of Return";
                font-size: 20px;
                font-weight: 700;
                horizontal-alignment: center;
            }
            percentage := LineEdit {
                font-size: 18px;
                horizontal-alignment: center;
                placeholder-text: "Expected Return (%)";
                height: 40px;
                min-width: 100px;
            }
        }

        Row {
            Text {
                text: "Enter Investment Period";
                font-size: 20px;
                font-weight: 700;
                horizontal-alignment: center;
            }
            years := LineEdit {
                font-size: 18px;
                horizontal-alignment: center;
                placeholder-text: "Time Horizon (Years)";
                height: 40px;
                min-width: 100px;
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 140px;
                    background: #efefef;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        horizontal-alignment: center;
                        text: root.results;
                    }
                }
            }

            Button {
                text: "Calculate";
                primary: true;
                height: 50px;
                clicked => {
                    calculate-salary(salary.text, initial.text, percentage.text, years.text);
                }
            }
        }
    }
}
